---
title: "ejemplo de tydeverse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# preparativos

## carga de paquetes
# dplyr y ggplot2


```{r}
library (dplyr)
library (ggplot2)


```


## carga de datos

```{r}

rios <-
  read.csv(file = 'https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/hidrologia/fdc/fdc.csv')


covid <- 
  read.csv(
    file='https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/minsalud/covid/ultimafecha_CSV_GENERAL.csv', 
    sep = ","
  )

```

## dplyr

### mutate

```{r}

# estructura del data frame

str(rios)

```

```{r}
# despliegue de los primeros registros
slice_head(rios, n= 10)

# despligue de los últimos registros

slice_tail(rios, n= 10)

# despliegue de una muestra aleatoria 
slice_sample (rios, n= 10)

```

```{r}

rios %>% slice_head(n=10) %>% slice_sample (n=10)

```

```{r}
rios %>% slice_head(n=10) %>% slice_tail(n=2)

```
```{r}
slice_tail (slice_head (rios, n=10) , n=2)

```

```{r}
# ejemplo mutate,  Cambio de nombre de las columnas mediante rename()
rios <-
  rios %>%
  rename(fecha = Tiempo,
         pandora = Pandora.mm..637km2.,
         banano = Banano.mm..90km2.) %>% 
  mutate(fecha = as.Date(fecha, format = "%m/%d/%Y"),
         promedio = (pandora + banano) / 2)
slice_head(rios, n=10)
```
         
         
